import{a as S,S as y,i as l}from"./assets/vendor-BMHzDZyJ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function $(t,o){const n="https://pixabay.com",s="/api/",e=new URLSearchParams({key:"50274791-f4b76ab6fee4d49d8c558ca21",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),r=`${n}${s}?${e}`;try{const a=await S.get(r);if(!a.data||!a.data.hits)throw new Error("Невірна відповідь від API");return{hits:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.log("Помилка при запиті до Pixabay:",a),a}}const m=document.querySelector(".gallery"),R=new y(".gallery a"),h=document.querySelector(".loader-container");async function q(t){const o=t.map(n=>{const{webformatURL:s,largeImageURL:e,tags:r,likes:a,views:L,comments:v,downloads:P}=n;return`
        <li><a class="gallery-link" href="${e}">
          <div class="gallery-item">
            <img class="gallery-image" src="${s}" alt="${r}" loading="lazy" />
            <div class="gallery-info">
              <p><b>Likes:</b> ${a}</p>
              <p><b>Views:</b> ${L}</p>
              <p><b>Comments:</b> ${v}</p>
              <p><b>Downloads:</b> ${P}</p>
            </div>
          </div>
        </a></li>
      `}).join("");m.insertAdjacentHTML("beforeend",o),R.refresh()}function H(){m.innerHTML=""}function p(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const g=document.querySelector(".gallery"),I=document.querySelector(".form"),c=document.querySelector(".load-more");let i=1,d="",u=0,f=0,x=new y(".gallery-item a",{captionsData:"alt",captionDelay:250});I.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(o===""){l.show({title:"Warning",message:"Please enter a search term before submitting!",position:"topRight",color:"yellow"}),t.target.reset();return}o!==d&&(i=1,d=o,u=0,H()),p(),await w(),b(),t.target.reset()});c.addEventListener("click",async()=>{i+=1,p(),await w(),b()});async function w(){try{const{hits:t,totalHits:o}=await $(d,i);if(i===1&&(f=o),t.length===0&&i===1){l.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}),c.style.display="none";return}const n=q(t);g.insertAdjacentHTML("beforeend",n),x.refresh(),u+=t.length;const s=g.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}u>=f?(c.style.display="none",l.show({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):c.style.display="block"}catch(t){l.show({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",color:"red"}),console.error("Помилка при запиті:",t)}}console.log("hi");
//# sourceMappingURL=index.js.map
