import{a as P,S as m,i as l}from"./assets/vendor-BMHzDZyJ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function $(t,r){const s="https://pixabay.com",n="/api/",e=new URLSearchParams({key:"50274791-f4b76ab6fee4d49d8c558ca21",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}),o=`${s}${n}?${e}`;try{const a=await P.get(o);if(!a.data||!a.data.hits)throw new Error("Невірна відповідь від API");return{hits:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.log("Помилка при запиті до Pixabay:",a),a}}const y=document.querySelector(".gallery"),q=new m(".gallery a"),f=document.querySelector(".loader-container");document.querySelector(".load-more");async function R(t){const r=t.map(s=>{const{webformatURL:n,largeImageURL:e,tags:o,likes:a,views:L,comments:v,downloads:S}=s;return`
        <li><a class="gallery-link" href="${e}">
          <div class="gallery-item">
            <img class="gallery-image" src="${n}" alt="${o}" loading="lazy" />
            <div class="gallery-info">
              <p><b>Likes:</b> ${a}</p>
              <p><b>Views:</b> ${L}</p>
              <p><b>Comments:</b> ${v}</p>
              <p><b>Downloads:</b> ${S}</p>
            </div>
          </div>
        </a></li>
      `}).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function H(){y.innerHTML=""}function h(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}const b=document.querySelector(".gallery"),I=document.querySelector(".form"),c=document.querySelector(".load-more");let i=1,d="",u=0,g=0,x=new m(".gallery-item a",{captionsData:"alt",captionDelay:250});I.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(r===""){l.show({title:"Warning",message:"Please enter a search term before submitting!",position:"topRight",color:"yellow"}),t.target.reset();return}r!==d&&(i=1,d=r,u=0,H()),h(),await w(),p(),t.target.reset()});c.addEventListener("click",async()=>{i+=1,h(),await w(),p();const t=b.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}});async function w(){try{const{hits:t,totalHits:r}=await $(d,i);if(i===1&&(g=r),t.length===0&&i===1){l.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}),c.style.display="none";return}const s=R(t);b.insertAdjacentHTML("beforeend",s),x.refresh(),u+=t.length,u>=g?(c.style.display="none",l.show({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):c.style.display="block"}catch(t){l.show({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",color:"red"}),console.error("Помилка при запиті:",t)}}
//# sourceMappingURL=index.js.map
